### ISSUE TITLE
$this when not in object context

### ISSUE THREAD

**Issue by james0r** [lukapeharda/tailwindcss-color-palette-generator#1]
Getting

```
Fatal error: Uncaught Error: Using $this when not in object context in /Users/jamesauble/Projects/wauble/wp-content/themes/wauble-tailwind/vendor/lukapeharda/tailwindcss-color-palette-generator/src/Color.php:85 Stack trace: #0 /Users/jamesauble/Projects/wauble/wp-content/themes/wauble-tailwind/template-parts/theme-css-vars.php(9): LukaPeharda\TailwindCssColorPaletteGenerator\Color::fromRgb(255, 255, 0) #1 /Users/jamesauble/Projects/wauble/wp-includes/template.php(772): require('/Users/jamesaub...') #2 /Users/jamesauble/Projects/wauble/wp-includes/template.php(716): load_template('/Users/jamesaub...', false, Array) #3 /Users/jamesauble/Projects/wauble/wp-includes/general-template.php(204): locate_template(Array, true, false, Array) #4 /Users/jamesauble/Projects/wauble/wp-content/themes/wauble-tailwind/template-parts/header.php(8): get_template_part('template-parts/...') #5 /Users/jamesauble/Projects/wauble/wp-includes/template.php(772): require('/Users/jamesaub...') #6 /Users/jamesauble/Projects/wauble/wp-includes/template.php(716): load_template('/Users/jamesaub...', false, Array) #7 /Users/jamesauble/Projects/wauble/wp-includes/general-template.php(204): locate_template(Array, true, false, Array) #8 /Users/jamesauble/Projects/wauble/wp-content/themes/wauble-tailwind/front-page.php(1): get_template_part('template-parts/...') #9 /Users/jamesauble/Projects/wauble/wp-includes/template-loader.php(106): include('/Users/jamesaub...') #10 /Users/jamesauble/Projects/wauble/wp-blog-header.php(19): require_once('/Users/jamesaub...') #11 /Users/jamesauble/Projects/wauble/index.php(17): require('/Users/jamesaub...') #12 {main} thrown in /Users/jamesauble/Projects/wauble/wp-content/themes/wauble-tailwind/vendor/lukapeharda/tailwindcss-color-palette-generator/src/Color.php on line 85
```

This some new strictness with PHP 8? I thought you couldn't use $this in a static function but I'm not very great at PHP OOP.

**Comment by lukapeharda** [comment]
Hi James,

no, this was not an error regarding PHP 8 but a plain bug. Thank you for reporting this. It is fixed in version 0.3.1 so please update it.

Kind regards,
Luka Peharda
